version: '3.7'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/usr/nodejs2022Q4
      - /usr/nodejs2022Q4/node_modules
    command: npm run start:dev
    restart: always
    ports:
    - ${PORT}:${PORT}
    environment:
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_HOST=db
    networks:
      - back
  db:
    image: anton/pg
    build: ./database
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    networks:
      - back
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
networks:
  back:
volumes:
  pgdata:
