version: '3.8'

services:
  db:
    container_name: postgres-ant
    build: ./database
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    ports:
    - ${TYPEORM_PORT}:${TYPEORM_PORT}
  backend:
    container_name: backend-ant
    build:
      context: ./
    depends_on:
      - db
    restart: unless-stopped
    ports:
    - ${PORT}:${PORT}
    environment:
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
      - TYPEORM_PORT=${TYPEORM_PORT}
      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
      - TYPEORM_HOST=db
